dist: xenial
sudo: required

os:
- linux
language: python
python:
  - 2.7
  - 3.6
  
before_install:
-sudo apt-get update
-sudo apt-get install build-essential python-dev libnetfilter-queue-dev

install: 
-pip3 install -r requirements.txt
script:
-sudo python setup.py install
-sudo SecureTea.py
